<a href="https://colab.research.google.com/github/Shilpa-collab-bot/Shilpa-collab-bot-/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [ ]:
pd.Series([1,2,3,4])

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
pd.Series(['hai','hello','pandas'],name='strings')

0       hai
1     hello
2    pandas
Name: strings, dtype: object

In [ ]:
pd.Series([chr(i+97) for i in np.arange(0,26)])

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [ ]:
pd.Series([chr(i+65) for i in np.arange(0,26)])

0     A
1     B
2     C
3     D
4     E
5     F
6     G
7     H
8     I
9     J
10    K
11    L
12    M
13    N
14    O
15    P
16    Q
17    R
18    S
19    T
20    U
21    V
22    W
23    X
24    Y
25    Z
dtype: object

In [ ]:
pd.Series([chr(i) for i in range(97,123)])

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [ ]:
pd.Series([chr(i) for i in range(65,91)])

0     A
1     B
2     C
3     D
4     E
5     F
6     G
7     H
8     I
9     J
10    K
11    L
12    M
13    N
14    O
15    P
16    Q
17    R
18    S
19    T
20    U
21    V
22    W
23    X
24    Y
25    Z
dtype: object

In [ ]:
#DataFrame
#syntax:val=pd.DataFrame(dict)
d={"Ename":['kala','Hari','roopa','jagan'],"Eid":[201,202,573,900],'dept':['python','DSA','DS','Ciber security']}
df=pd.DataFrame(d)
df

   Ename  Eid            dept
0   kala  201          python
1   Hari  202             DSA
2  roopa  573              DS
3  jagan  900  Ciber security

In [ ]:
#accesing a one column
df['Ename']

0     kala
1     Hari
2    roopa
3    jagan
Name: Ename, dtype: object

In [ ]:
#accessing paticular value
#syntax:var['col_name'][inde_value]
df['Ename'][0]
df['Eid'][0]

np.int64(201)

In [ ]:
#adding new series to the data frame to the exisiting
#synatc:var['col_name']=values
df['Salary']=['10lpa','30pla','50lpa','1cr']
df

   Ename  Eid            dept Salary
0   kala  201          python  10lpa
1   Hari  202             DSA  30pla
2  roopa  573              DS  50lpa
3  jagan  900  Ciber security    1cr

In [ ]:
#filter


a=pd.Series([12,50,90,43])
a[a>20]

1    50
2    90
3    43
dtype: int64

In [ ]:
a=pd.Series([chr(i) for i in range(65,91)])
a[a>='P']

15    P
16    Q
17    R
18    S
19    T
20    U
21    V
22    W
23    X
24    Y
25    Z
dtype: object

In [ ]:
a=pd.Series([chr(i) for i in range(97,123)])
a[a<'k']

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
dtype: object

In [ ]:
a[a>'p']

16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [ ]:
df=pd.read_csv('/content/titanic.csv')
df

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [ ]:
#head()
#df.head()
df.head()
df.head(10)

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
5,5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
6,6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,77.9583,D7,S,1
7,7,1,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0000,A36,S,0
8,8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2,0,11769,51.4792,C101,S,1
9,9,1,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,49.5042,NaN,C,0

In [ ]:
#tail()
df.tail()
df.tail(10)

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1299,1299,3,"Yasbeck, Mr. Antoni",male,27.0,1,0,2659,14.4542,NaN,C,0
1300,1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,1
1301,1301,3,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.2250,NaN,C,0
1302,1302,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C,0
1303,1303,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C,0
1304,1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [ ]:
#info()
#it will give the total information about it
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  1309 non-null   int64
 1   pclass      1309 non-null   int64
 2   name        1309 non-null   object
 3   sex         1309 non-null   object
 4   age         1046 non-null   float64
 5   sibsp       1309 non-null   int64
 6   parch       1309 non-null   int64
 7   ticket      1309 non-null   object
 8   fare        1308 non-null   float64
 9   cabin       295 non-null    object
 10  embarked    1307 non-null   object
 11  survived    1309 non-null   int64
dtypes: float64(2), int64(5), object(5)
memory usage: 122.8+ KB

In [ ]:
#describe
#it will perfrom statisticall operations on integer values
df.describe()

,Unnamed: 0,pclass,age,sibsp,parch,fare,survived
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,1309.000000
mean,654.000000,2.294882,29.881135,0.498854,0.385027,33.295479,0.381971
std,378.020061,0.837836,14.413500,1.041658,0.865560,51.758668,0.486055
min,0.000000,1.000000,0.166700,0.000000,0.000000,0.000000,0.000000
25%,327.000000,2.000000,21.000000,0.000000,0.000000,7.895800,0.000000
50%,654.000000,3.000000,28.000000,0.000000,0.000000,14.454200,0.000000
75%,981.000000,3.000000,39.000000,1.000000,0.000000,31.275000,1.000000
max,1308.000000,3.000000,80.000000,8.000000,9.000000,512.329200,1.000000

In [ ]:
df['pclass'].describe()

count    1309.000000
mean        2.294882
std         0.837836
min         1.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         3.000000
Name: pclass, dtype: float64

In [ ]:
df.describe(include=object)

                    name   sex    ticket        cabin embarked
count               1309  1309      1309          295     1307
unique              1307     2       929          186        3
top     Kelly, Mr. James  male  CA. 2343  C23 C25 C27        S
freq                   2   843        11            6      914

In [ ]:
#shape
#syntax:df.shape
df.shape

(1309, 12)

In [ ]:
#columns
#syn:df.columns
df.columns

Index(['Unnamed: 0', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch',
       'ticket', 'fare', 'cabin', 'embarked', 'survived'],
      dtype='object')

In [ ]:
#unique()
#syntax:df['col_name'].unique()
df['pclass'].unique()

array([1, 2, 3])

In [ ]:
df['survived'].unique()

array([1, 0])

In [ ]:
df['sex'].unique()

array(['female', 'male'], dtype=object)

In [ ]:
var=pd.read_csv('student_data.csv')
var

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74.0
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,5 - 10,69,90,88.0
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91.0
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,5 - 10,45,56,42.0
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,5 - 10,76,78,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11035,693,male,group D,high school,standard,none,married,sometimes,yes,1.0,school_bus,5 - 10,68,66,59.0
11036,694,male,NaN,some high school,standard,none,married,sometimes,yes,3.0,school_bus,5 - 10,86,83,76.0
11037,695,male,group C,NaN,free/reduced,none,married,regularly,yes,3.0,school_bus,5 - 10,53,48,52.0
11038,696,female,group B,high school,standard,completed,divorced,sometimes,yes,0.0,private,5 - 10,75,89,80.0
11039,697,female,group C,bachelor's degree,free/reduced,completed,divorced,sometimes,yes,2.0,school_bus,5 - 10,75,8,NaN

In [ ]:
var.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11040 entries, 0 to 11039
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           11040 non-null  int64
 1   Gender               11040 non-null  object
 2   EthnicGroup          10375 non-null  object
 3   ParentEduc           10382 non-null  object
 4   LunchType            11040 non-null  object
 5   TestPrep             10381 non-null  object
 6   ParentMaritalStatus  10605 non-null  object
 7   PracticeSport        10816 non-null  object
 8   IsFirstChild         10678 non-null  object
 9   NrSiblings           10472 non-null  float64
 10  TransportMeans       9900 non-null   object
 11  WklyStudyHours       10701 non-null  object
 12  MathScore            11040 non-null  int64
 13  ReadingScore         11040 non-null  int64
 14  WritingScore         11039 non-null  float64
dtypes: float64(2), int64(3), object(10)
memory usage: 1.3+ MB

In [ ]:
var.head()
var.head(10)

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
0,0,female,NaN,bachelor's degree,standard,none,married,regularly,yes,3.0,school_bus,< 5,71,71,74.0
1,1,female,group C,some college,standard,NaN,married,sometimes,yes,0.0,NaN,5 - 10,69,90,88.0
2,2,female,group B,master's degree,standard,none,single,sometimes,yes,4.0,school_bus,< 5,87,93,91.0
3,3,male,group A,associate's degree,free/reduced,none,married,never,no,1.0,NaN,5 - 10,45,56,42.0
4,4,male,group C,some college,standard,none,married,sometimes,yes,0.0,school_bus,5 - 10,76,78,75.0
5,5,female,group B,associate's degree,standard,none,married,regularly,yes,1.0,school_bus,5 - 10,73,84,79.0
6,6,female,group B,some college,standard,completed,widowed,never,no,1.0,private,5 - 10,85,93,89.0
7,7,male,group B,some college,free/reduced,none,married,sometimes,yes,1.0,private,> 10,41,43,39.0
8,8,male,group D,high school,free/reduced,completed,single,sometimes,no,3.0,private,> 10,65,64,68.0
9,9,female,group B,high school,free/reduced,none,married,regularly,yes,NaN,private,< 5,37,59,50.0

In [ ]:
var.tail()
var.tail(10)

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,ParentMaritalStatus,PracticeSport,IsFirstChild,NrSiblings,TransportMeans,WklyStudyHours,MathScore,ReadingScore,WritingScore
11030,688,male,group B,some college,free/reduced,none,single,regularly,yes,1.0,NaN,5 - 10,42,47,47.0
11031,689,female,group C,some high school,free/reduced,none,married,sometimes,yes,0.0,NaN,> 10,44,57,52.0
11032,690,male,group B,associate's degree,standard,completed,married,sometimes,yes,0.0,school_bus,< 5,69,68,71.0
11033,691,female,group D,associate's degree,free/reduced,none,divorced,sometimes,yes,1.0,school_bus,< 5,65,76,72.0
11034,692,male,group B,some high school,standard,none,married,sometimes,yes,NaN,school_bus,< 5,81,81,77.0
11035,693,male,group D,high school,standard,none,married,sometimes,yes,1.0,school_bus,5 - 10,68,66,59.0
11036,694,male,NaN,some high school,standard,none,married,sometimes,yes,3.0,school_bus,5 - 10,86,83,76.0
11037,695,male,group C,NaN,free/reduced,none,married,regularly,yes,3.0,school_bus,5 - 10,53,48,52.0
11038,696,female,group B,high school,standard,completed,divorced,sometimes,yes,0.0,private,5 - 10,75,89,80.0
11039,697,female,group C,bachelor's degree,free/reduced,completed,divorced,sometimes,yes,2.0,school_bus,5 - 10,75,8,NaN

In [ ]:
var.shape

(11040, 15)

In [ ]:
var.columns

Index(['Unnamed: 0', 'Gender', 'EthnicGroup', 'ParentEduc', 'LunchType',
       'TestPrep', 'ParentMaritalStatus', 'PracticeSport', 'IsFirstChild',
       'NrSiblings', 'TransportMeans', 'WklyStudyHours', 'MathScore',
       'ReadingScore', 'WritingScore'],
      dtype='object')

In [ ]:
var.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11040 entries, 0 to 11039
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           11040 non-null  int64
 1   Gender               11040 non-null  object
 2   EthnicGroup          10375 non-null  object
 3   ParentEduc           10382 non-null  object
 4   LunchType            11040 non-null  object
 5   TestPrep             10381 non-null  object
 6   ParentMaritalStatus  10605 non-null  object
 7   PracticeSport        10816 non-null  object
 8   IsFirstChild         10678 non-null  object
 9   NrSiblings           10472 non-null  float64
 10  TransportMeans       9900 non-null   object
 11  WklyStudyHours       10701 non-null  object
 12  MathScore            11040 non-null  int64
 13  ReadingScore         11040 non-null  int64
 14  WritingScore         11039 non-null  float64
dtypes: float64(2), int64(3), object(10)
memory usage: 1.3+ MB

In [ ]:
var['MathScore'].unique()

array([ 71,  69,  87,  45,  76,  73,  85,  41,  65,  37,  58,  40,  66,
        80,  48,  88,  18,  46,  50,  42,  74,  75,  70,  63,  56,  97,
        81,  51,  77,  53,  59,  60,  67,  82,  54,  33,  84,  52,  61,
         0,  39,  62,  64,  47,  44,  28,  49,  57,  27,  68,  79, 100,
        72,  98,  55,  90,  86,  89,  21,  96,  91,  99,  83,  35,  43,
        93,  78,  94,  36,  29,  23,  92,  26,  38,  95,  30,  32,   8,
        34,  31,  25,  22,  17,  20,  16,  19,  24,  15,  11,  12,  13])

In [ ]:
var.describe()

         Unnamed: 0    NrSiblings     MathScore  ReadingScore  WritingScore
count  11040.000000  10472.000000  11040.000000  11040.000000  11039.000000
mean     491.028804      2.125000     66.689493     69.441757     68.449316
std      286.041837      1.471642     15.442964     14.747144     15.435190
min        0.000000      0.000000      0.000000      8.000000      6.000000
25%      245.000000      1.000000     56.000000     59.000000     58.000000
50%      488.000000      2.000000     67.000000     70.000000     69.000000
75%      733.000000      3.000000     78.000000     80.000000     79.000000
max      999.000000      7.000000    100.000000    100.000000    100.000000

In [ ]:
var['NrSiblings'].unique()

array([ 3.,  0.,  4.,  1., nan,  2.,  5.,  7.,  6.])

In [ ]:
var['TestPrep'].describe()

count     10381
unique        2
top        none
freq       6843
Name: TestPrep, dtype: object

In [ ]:
var['PracticeSport'].describe()

count         10816
unique            3
top       sometimes
freq           5478
Name: PracticeSport, dtype: object

In [ ]:
pclass1=df[df['pclass']==1]
pclass1

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
318,318,1,"Williams-Lambert, Mr. Fletcher Fellows",male,NaN,0,0,113510,35.0000,C128,S,0
319,319,1,"Wilson, Miss. Helen Alice",female,31.0000,0,0,16966,134.5000,E39 E41,C,1
320,320,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S,1
321,321,1,"Wright, Mr. George",male,62.0000,0,0,113807,26.5500,NaN,S,0
322,322,1,"Young, Miss. Marie Grice",female,36.0000,0,0,PC 17760,135.6333,C32,C,1

In [ ]:
pclass1['pclass'].unique()

array([1])

In [ ]:
df[(df['pclass']==2)&(df['age']>25)]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
323,323,2,"Abelson, Mr. Samuel",male,30.0,1,0,P/PP 3381,24.00,NaN,C,0
324,324,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.00,NaN,C,1
325,325,2,"Aldworth, Mr. Charles Augustus",male,30.0,0,0,248744,13.00,NaN,S,0
328,328,2,"Angle, Mr. William A",male,34.0,1,0,226875,26.00,NaN,S,0
329,329,2,"Angle, Mrs. William A (Florence ""Mary"" Agnes H...",female,36.0,1,0,226875,26.00,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
592,592,2,"West, Mr. Edwy Arthur",male,36.0,1,2,C.A. 34651,27.75,NaN,S,0
593,593,2,"West, Mrs. Edwy Arthur (Ada Mary Worth)",female,33.0,1,2,C.A. 34651,27.75,NaN,S,1
594,594,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.50,NaN,S,0
596,596,2,"Wilhelms, Mr. Charles",male,31.0,0,0,244270,13.00,NaN,S,1
598,598,2,"Wright, Miss. Marion",female,26.0,0,0,220844,13.50,NaN,S,1

In [ ]:
df[(df['pclass']==2)&(df['age']>20)&(df['survived']==1)]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
324,324,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.00,NaN,C,1
329,329,2,"Angle, Mrs. William A (Florence ""Mary"" Agnes H...",female,36.0,1,0,226875,26.00,NaN,S,1
333,333,2,"Ball, Mrs. (Ada E Hall)",female,36.0,0,0,28551,13.00,D,S,1
336,336,2,"Beane, Mr. Edward",male,32.0,1,0,2908,26.00,NaN,S,1
342,342,2,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)",female,36.0,0,3,230136,39.00,F4,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
586,586,2,"Weisz, Mrs. Leopold (Mathilde Francoise Pede)",female,29.0,1,0,228414,26.00,NaN,S,1
589,589,2,"Wells, Mrs. Arthur Henry (""Addie"" Dart Trevaskis)",female,29.0,0,2,29103,23.00,NaN,S,1
593,593,2,"West, Mrs. Edwy Arthur (Ada Mary Worth)",female,33.0,1,2,C.A. 34651,27.75,NaN,S,1
596,596,2,"Wilhelms, Mr. Charles",male,31.0,0,0,244270,13.00,NaN,S,1
598,598,2,"Wright, Miss. Marion",female,26.0,0,0,220844,13.50,NaN,S,1

In [ ]:
df

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [ ]:
df[(df['parch']==1)]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
16,16,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C,0
17,17,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C,1
20,20,1,"Beckwith, Mr. Richard Leonard",male,37.0,1,1,11751,52.5542,D35,S,1
21,21,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,1
36,36,1,"Bowerman, Miss. Elsie Edith",female,22.0,0,1,113505,55.0000,E33,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1257,1257,3,"Touma, Miss. Maria Youssef",female,9.0,1,1,2650,15.2458,NaN,C,1
1262,1262,3,"van Billiard, Master. James William",male,NaN,1,1,A/5. 851,14.5000,NaN,S,0
1263,1263,3,"van Billiard, Master. Walter John",male,11.5,1,1,A/5. 851,14.5000,NaN,S,0
1266,1266,3,"Van Impe, Mr. Jean Baptiste",male,36.0,1,1,345773,24.1500,NaN,S,0
1267,1267,3,"Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...",female,30.0,1,1,345773,24.1500,NaN,S,0

In [ ]:
df[(df['sex']=='male')&(df['age']>=20)&(df['age']<=40)]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
3,3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.5500,C22 C26,S,0
7,7,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,0
16,16,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C,0
19,19,1,"Beattie, Mr. Thomson",male,36.0,0,0,13050,75.2417,C6,C,0
20,20,1,"Beckwith, Mr. Richard Leonard",male,37.0,1,1,11751,52.5542,D35,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1298,3,"Wittevrongel, Mr. Camille",male,36.0,0,0,345771,9.5000,NaN,S,0
1299,1299,3,"Yasbeck, Mr. Antoni",male,27.0,1,0,2659,14.4542,NaN,C,0
1306,1306,3,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,0
1307,1307,3,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,0
1308,1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,0

In [ ]:
df[(df['sex']=='female')&(df['survived']==1)]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
6,6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
11,11,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C,1
12,12,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1260,1260,3,"Turja, Miss. Anna Sofia",female,18.0,0,0,4138,9.8417,NaN,S,1
1261,1261,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,1
1286,1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
1300,1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,1

In [ ]:
df[(df['sex']=='female')&(df['age']>=20)&(df['age']>=20)]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
4,4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,0
6,6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
12,12,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1261,1261,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,1
1267,1267,3,"Van Impe, Mrs. Jean Baptiste (Rosalie Paula Go...",female,30.0,1,1,345773,24.1500,NaN,S,0
1276,1276,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S,0
1286,1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1

In [ ]:
df[(df['sex']=='male')&(df['survived']==1)]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
5,5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
14,14,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0000,0,0,27042,30.0000,A23,S,1
20,20,1,"Beckwith, Mr. Richard Leonard",male,37.0000,1,1,11751,52.5542,D35,S,1
22,22,1,"Behr, Mr. Karl Howell",male,26.0000,0,0,111369,30.0000,C148,C,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1238,1238,3,"Tenglin, Mr. Gunnar Isidor",male,25.0000,0,0,350033,7.7958,NaN,S,1
1240,1240,3,"Thomas, Master. Assad Alexander",male,0.4167,0,1,2625,8.5167,NaN,C,1
1254,1254,3,"Tornquist, Mr. William Henry",male,25.0000,0,0,LINE,0.0000,NaN,S,1
1256,1256,3,"Touma, Master. Georges Youssef",male,7.0000,1,1,2650,15.2458,NaN,C,1
1277,1277,3,"Vartanian, Mr. David",male,22.0000,0,0,2658,7.2250,NaN,C,1

In [ ]:
df[(df['sex']=='female')&(df['age']>20)&(df['survived']==1)]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
6,6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
12,12,1,"Aubart, Mme. Leontine Pauline",female,24.0,0,0,PC 17477,69.3000,B35,C,1
13,13,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1223,1223,3,"Stanley, Miss. Amy Zillah Elsie",female,23.0,0,0,CA. 2314,7.5500,NaN,S,1
1258,1258,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29.0,0,2,2650,15.2458,NaN,C,1
1261,1261,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,1
1286,1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1

In [ ]:
df[(df['pclass']==3)&(df['sex']=='male')&(df['age']>25)&(df['survived']==1)]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
613,613,3,"Albimona, Mr. Nassef Cassem",male,26.0,0,0,2699,18.7875,NaN,C,1
630,630,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.0,0,0,350043,7.7958,NaN,S,1
674,674,3,"Bing, Mr. Lee",male,32.0,0,0,1601,56.4958,NaN,S,1
714,714,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S,1
742,742,3,"Dahl, Mr. Karl Edwart",male,45.0,0,0,7598,8.0500,NaN,S,1
746,746,3,"Daly, Mr. Eugene Patrick",male,29.0,0,0,382651,7.7500,NaN,Q,1
758,758,3,"de Messemaeker, Mr. Guillaume Joseph",male,36.5,1,0,345572,17.4000,NaN,S,1
760,760,3,"de Mulder, Mr. Theodore",male,30.0,0,0,345774,9.5000,NaN,S,1
857,857,3,"Hedman, Mr. Oskar Arvid",male,27.0,0,0,347089,6.9750,NaN,S,1
880,880,3,"Jalsevac, Mr. Ivan",male,29.0,0,0,349240,7.8958,NaN,C,1
889,889,3,"Johansson Palmquist, Mr. Oskar Leander",male,26.0,0,0,347070,7.7750,NaN,S,1
905,905,3,"Jonsson, Mr. Carl",male,32.0,0,0,350417,7.8542,NaN,S,1
909,909,3,"Jussila, Mr. Eiriik",male,32.0,0,0,STON/O 2. 3101286,7.9250,NaN,S,1
917,917,3,"Karun, Mr. Franz",male,39.0,0,1,349256,13.4167,NaN,C,1
935,935,3,"Kink-Heilmann, Mr. Anton",male,29.0,3,1,315153,22.0250,NaN,S,1
949,949,3,"Lang, Mr. Fang",male,26.0,0,0,1601,56.4958,NaN,S,1
978,978,3,"Lulic, Mr. Nikola",male,27.0,0,0,315098,8.6625,NaN,S,1
981,981,3,"Lundstrom, Mr. Thure Edvin",male,32.0,0,0,350403,7.5792,NaN,S,1
1064,1064,3,"Niskanen, Mr. Juha",male,39.0,0,0,STON/O 2. 3101289,7.9250,NaN,S,1
1088,1088,3,"Olsson, Mr. Oscar Wilhelm",male,32.0,0,0,347079,7.7750,NaN,S,1
1131,1131,3,"Pickard, Mr. Berk (Berk Trembisky)",male,32.0,0,0,SOTON/O.Q. 392078,8.0500,E10,S,1
1196,1196,3,"Sheerlinck, Mr. Jan Baptist",male,29.0,0,0,345779,9.5000,NaN,S,1
1228,1228,3,"Stranden, Mr. Juho",male,31.0,0,0,STON/O 2. 3101288,7.9250,NaN,S,1
1233,1233,3,"Sundman, Mr. Johan Julian",male,44.0,0,0,STON/O 2. 3101269,7.9250,NaN,S,1

In [ ]:
#mistake1)to get the data of male passangers who age is 25 to 40 and survived in pclass 1 and 2

df[(df['pclass']==1)&(df['pclass']==2)&(df['sex']=='male')&(df['age']>=25)&(df['age']<=40) &(df['survived']==1)]

Empty DataFrame
Columns: [Unnamed: 0, pclass, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, survived]
Index: []

In [ ]:
df[(df['sex']=='female')]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
2,2,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,0
4,4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,0
6,6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1286,1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
1300,1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,1
1304,1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0

In [ ]:
df[(df['sex']=='male')]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
3,3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
5,5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
7,7,1,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0000,A36,S,0
9,9,1,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,49.5042,NaN,C,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1302,1302,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C,0
1303,1303,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C,0
1306,1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [ ]:
df[(df['age']>30)&(df['parch']==1)&(df['sibsp']==1)&(df['pclass']==2)]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
351,351,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,29750,39.0000,NaN,S,0
352,352,2,"Brown, Mrs. Thomas William Solomon (Elizabeth ...",female,40.0,1,1,29750,39.0000,NaN,S,1
378,378,2,"Collyer, Mr. Harvey",male,31.0,1,1,C.A. 31921,26.2500,NaN,S,0
379,379,2,"Collyer, Mrs. Harvey (Charlotte Annie Tate)",female,31.0,1,1,C.A. 31921,26.2500,NaN,S,1
399,399,2,"Drew, Mr. James Vivian",male,42.0,1,1,28220,32.5000,NaN,S,0
400,400,2,"Drew, Mrs. James Vivian (Lulu Thorne Christian)",female,34.0,1,1,28220,32.5000,NaN,S,1
435,435,2,"Hart, Mr. Benjamin",male,43.0,1,1,F.C.C. 13529,26.2500,NaN,S,0
436,436,2,"Hart, Mrs. Benjamin (Esther Ada Bloomfield)",female,45.0,1,1,F.C.C. 13529,26.2500,NaN,S,1
493,493,2,"Mallet, Mr. Albert",male,31.0,1,1,S.C./PARIS 2079,37.0042,NaN,C,0

In [ ]:
df[(df['survived']==1)]

,Unnamed: 0,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
5,5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
6,6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,77.9583,D7,S,1
8,8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2,0,11769,51.4792,C101,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1261,1261,3,"Turkula, Mrs. (Hedwig)",female,63.0000,0,0,4134,9.5875,NaN,S,1
1277,1277,3,"Vartanian, Mr. David",male,22.0000,0,0,2658,7.2250,NaN,C,1
1286,1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0000,0,0,2688,7.2292,NaN,C,1
1290,1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0000,1,0,363272,7.0000,NaN,S,1
1300,1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0000,1,0,2659,14.4542,NaN,C,1